# Generated by Django 4.2.6 on 2023-10-08 17:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(default='coming-soon', max_length=20)),
                ('gameImg', models.ImageField(upload_to=api.models.upload_poster)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('tourney_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('org_name', models.CharField(max_length=50)),
                ('org_img', models.ImageField(upload_to=api.models.upload_orgimg)),
                ('game_id', models.IntegerField()),
                ('banner', models.ImageField(upload_to=api.models.upload_slide)),
                ('event_place', models.CharField(max_length=50)),
                ('event_prize', models.CharField(max_length=20)),
                ('event_url', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField()),
                ('event_fees', models.CharField(max_length=20)),
                ('match_type', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
