# Generated by Django 4.2.6 on 2023-10-15 17:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('slide_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(default='coming-soon', max_length=20)),
                ('slide_img', models.ImageField(upload_to=api.models.upload_slide)),
            ],
        ),
    ]
