# Generated by Django 4.2.6 on 2023-10-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='path',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='banner',
        ),
    ]
