# Generated by Django 4.2.6 on 2023-10-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_game_path_remove_tourney_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourney',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
